### ISSUE TITLE
Package on pypi.python.org does not include any of the code.

### ISSUE THREAD

**Issue by nanorepublica** [benhamill/cetacean-python#2]
Therefore generates the following error when doing `pip install Cetacean`:

```
Downloading/unpacking Cetacean
  Downloading Cetacean-1.0.0.tar.gz
  Running setup.py egg_info for package Cetacean
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/vagrant/build/Cetacean/setup.py", line 12, in <module>
        import cetacean
    ImportError: No module named cetacean
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/vagrant/build/Cetacean/setup.py", line 12, in <module>

    import cetacean

ImportError: No module named cetacean

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/vagrant/.pip/pip.log
```

Please could you correctly upload your code to pypi or remove the entry if you don't want it published there.

**Comment by christophlingg** [comment]
same problem here, please adopt the PR @benhamill 

without pip we can't use this library in our project, it's used by different developers and CI machines. Manual setup is a real pain. I am going on with `pip install dougrain`

**Comment by benhamill** [comment]
Just saw this. Not sure how I missed it. Thanks, y'all. I'll push a new version in a bit.

**Comment by christophlingg** [comment]
great, it works like a charm. thanks
